- .flowconfig
- .jscsrc
- .jshintrc
- README.md
- gulpfile.js
- karma.conf.js
- package.json
- spec/components/admin-filter.spec.js
- spec/components/admin-list.spec.js
- spec/components/admin-project-details-card.spec.js
- spec/components/admin-project-details-explanation.spec.js
- spec/components/admin-transaction-history.spec.js
- spec/components/admin-transactions.spec.js
- spec/components/project-card.spec.js
- spec/components/project-contributions-per-location-table.spec.js
- spec/components/project-reminder-count.spec.js
- spec/components/project-row.spec.js
- spec/components/team-members.spec.js
- spec/components/team-total.spec.js
- src/admin/contributions.js
Adding Flowtype and ES6 (through Babel) to our build pipeline.
Suggestion is that all new components adopt our new tools.
> Flow and es6

- src/contribution/projects-home.js
- src/models.js
This should make our API calls faster by removing the random order from
the database.
> Get 30 projects from the API for each home section, then pick 3 randomly.

- spec/components/admin-project-details-card.spec.js
- spec/components/project-card.spec.js
- spec/components/project-sidebar.spec.js
- spec/components/tooltip.spec.js
- spec/lib/mocks/project-details.mock.js
- spec/lib/mocks/project.mock.js
- src/c/admin-project-details-card.js
- src/c/project-about.js
- src/c/project-card.js
- src/c/project-contributions.js
- src/c/project-data-table.js
- src/c/project-mode.js
- src/c/project-sidebar.js
- src/c/tooltip.js
- src/h.js
> New project show

- src/root/projects-explore.js
- src/vms/project-filters.js
With the new projects endpoint everything will be fine
> Removes all time limitations that were created for performance reasons

- src/c/dropdown.js
- src/c/filter-dropdown.js
- src/c/project-main.js
- src/h.js
* Creates redrawHashChange helper to hook a redraw on window hashchange with an optional callback before
* Moves dropdown template to a helper function
> Preparing for project dashboard 

- bower.json
- gulpfile.js
- package.json
- spec/components/project-about.spec.js
- spec/components/project-contributions.spec.js
- spec/components/project-header.spec.js
- spec/components/project-highlight.spec.js
- spec/components/project-posts.spec.js
- spec/components/project-tabs.spec.js
- src/c/admin-external-action.js
- src/c/admin-reset-password.js
- src/c/project-about.js
- src/c/project-comments.js
- src/c/project-contributions.js
- src/c/project-header.js
- src/c/project-posts.js
- src/c/project-tabs.js
- src/root/flex.js
- src/root/projects-explore.js
- src/root/projects-home.js
- src/root/projects-show.js
- src/root/start.js
Whenever sharing state across a set of subcomponents, we should rely on `m.prop` to keep references right.
> Updates projects show to use propified version [fix #112222959]

- src/c/flex-project-details-explanation.js
- src/c/project-dashboard-menu.js
Do not deploy until PR for the rails side is ready.
> update copy for flex projects

- src/c/contribution-activities.js
- src/models.js
- src/root/projects-home.js
small box with last contributions activities
> Contribution activities

- src/c/contribution-activities.js
- src/c/search.js
- src/c/slider.js
- src/root/projects-home.js
- src/root/start.js
- src/vms/home.js
> Adds home slider

- src/c/admin-reset-password.js
- src/root/projects-explore.js
- src/root/projects-home.js
- src/vms/project-filters.js
- Testing locally I saw a measurable performance decrease.
> Removes recommended filters and starts ordering by score

- src/c/filter-dropdown.js
- src/c/filter-main.js
- src/c/project-contribution-report-content-card.js
- src/c/project-contribution-report-content.js
- src/c/project-contribution-report-header.js
- src/root/projects-contribution-report.js
- src/root/vms/projects-contribution-report-filter-vm.js
just basic list and filters using the project_contributions api endpoint
> New contribution reports basics

- src/models.js
- src/root/projects-explore.js
- src/vms/project-filters.js
> Finished projects

- src/c/signed-friend-facebook-connect.js
- src/c/user-follow-btn.js
- Add conect to fb btn when has no friends
- Add hover to unfollow btn
> Adjusts on follows

- src/c/dropdown.js
- src/c/filter-dropdown.js
- src/c/info-project-contribution-state-legend.js
- src/c/project-contribution-report-content-card.js
- src/c/project-contribution-report-content.js
- src/c/project-contribution-state-legend-modal.js
- src/root/projects-contribution-report.js
- src/vms/projects-contribution-report-vm.js
> Contribution report legend modal

- src/c/project-main.js
- src/c/project-posts.js
- src/c/project-tabs.js
- src/root/projects-show.js
- Added project post show page reusing the projectShow component
> Show post page

- src/c/facebook-button.js
- src/c/invite-emails-from-import.js
- src/c/project-email-invite.js
- src/c/project-google-contact-import.js
- src/c/project-invite-card.js
- src/models.js
- src/root/insights.js
- added project-invites component
> Project invites

- src/c/project-reminder.js
- src/c/project-sidebar.js
- Added friends ho contributed with project on project page
- Change project reminder icon and position (heart style)
> Friends on project show

- src/c/project-dashboard-menu.js
We need to reload page in rails to get cancel modal.
> do not user mithril route for insight

- spec/components/root/projects-payment.spec.js
- spec/lib/mocks/user-details.mock.js
- src/h.js
- src/root/projects-payment.js
- src/vms/payment-vm.js
- src/vms/user-vm.js
> add user info card on payment

- src/c/payment-credit-card.js
- src/vms/payment-vm.js
We need to get the credit card owner document when is BR
> Added cardOwnerDocument to creditCardFields

- src/c/menu-profile.js
- src/c/user-about-edit.js
- src/c/user-settings.js
- src/root/check-email.js
- src/root/thank-you.js
- src/root/users-edit.js
- Added public name on profile tab
- Moved email, password and account delete to user about tab
> Changes on user about edit

- src/c/big-input-card.js
- src/c/project-basics-edit.js
- src/c/project-budget-edit.js
- src/c/project-description-edit.js
- src/c/project-goal-edit.js
- src/vms/reward-vm.js
- Redraw to show loadings on project edit 
- Add more customizations for component bigInputCard
- Fixes budget size on project edit 
- Should show error on permalink field
> Small fixes

- src/c/project-basics-edit.js
- src/c/project-budget-edit.js
- src/c/project-card-edit.js
- src/c/project-dashboard-menu.js
- src/c/project-description-edit.js
- src/c/project-edit-save-btn.js
- src/c/project-goal-edit.js
- src/c/project-video-edit.js
- src/c/user-about-edit.js
- src/c/user-settings.js
- src/root/project-edit-basic.js
- src/root/project-edit-budget.js
- src/root/project-edit-card.js
- src/root/project-edit-description.js
- src/root/project-edit-goal.js
- src/root/project-edit-user-about.js
- src/root/project-edit-user-settings.js
- src/root/project-edit-video.js
- src/root/project-edit.js
- src/vms/project-vm.js
- src/vms/rails-errors-vm.js
Now we use ```railsErrorsVM.setRailsErrors()``` to set dashboard-wide errors and pass tab specific errors using ```railsErrorsVM.mapRailsErrors()```.
> fix rails errors [#144516929]

- src/c/project-basics-edit.js
- src/c/project-budget-edit.js
- src/c/project-card-edit.js
- src/c/project-description-edit.js
- src/c/project-edit-save-btn.js
- src/c/project-goal-edit.js
- src/c/project-video-edit.js
- src/c/user-about-edit.js
- src/c/user-settings.js
- src/vms/rails-errors-vm.js
Make sure validatePublish runs after form submit.
> fix timing issue with validate publish

- src/c/project-basics-edit.js
- src/h.js
This PR improves the input tag field usability, by addling state handler to different possible states of the field.
> Improves tags field UX

- src/c/project-basics-edit.js
Replace tag searching endpoint for tag_search and adds add on enter feature.
> Replace tag search endpoint, and add tag on enter

- src/c/project-basics-edit.js
- src/error.js
> debounces properly, adds number of tags rule

- src/c/edit-reward-card.js
Do not allow reward values with cents.
> disallow cents on reward edit value [#145891251]

- src/c/project-basics-edit.js
This moves the key press handler to the browser, so mithril only have to take care about tag options.
> Moves onkeyup event handling to dom

- src/c/project-data-stats.js
- src/c/project-header-title.js
- src/root/posts.js
- src/root/project-edit-reward.js
- src/root/project-edit.js
- src/root/project-preview.js
- src/root/projects-contribution.js
- src/root/projects-payment.js
- src/root/projects-show.js
- src/vms/payment-vm.js
- src/vms/project-basics-vm.js
- src/vms/project-vm.js
In some points we are fetching the currentProject over projectVM via data-parameters = hole project data, instead using for passing only ids like data-parameters = project_id, user_id...
This PR check the data parameters before load into currentProject prop
> Fixes when using data-parameters to get full project without async

- src/c/project-card.js
- src/c/project-sidebar.js
To avoid timezone on project-card and project sidebar status text
> Use project zone expires on card

- src/vms/payment-vm.js
Check if data.address is not undefined when calling for country
> should check if address object is defined before call for country

- src/c/reward-select-card.js
- src/vms/reward-vm.js
This fixes the minimum value issue by avoiding a duplicated call to rewardSelect.
> fixes reward contribution value properly [#146290765]

- src/root/projects-contribution.js
Adds a warning box to the contribution flow.
> Adds contribution warning box on contribution/new

- src/c/admin-balance-transfer-item.js
- src/c/user-balance-request-modal-content.js
- adjust missing i18n copy 
- added transfer id
> Balance copy

- src/c/dashboard-reward-card.js
- src/c/edit-reward-card.js
Makes some layout adjustments on project reward edit card.
> fixes edit reward cards

- src/c/admin-balance-transfer-item.js
- src/c/filter-date-range.js
- src/root/admin-balance-tranfers.js
- src/vms/balance-transfer-filter-vm.js
- Use date range filter instead date filter
- Added datemask on date range filter
- Use transfer_limit_date on balance transfer item
- Add total when confirming actions
> Balance filters

- src/c/dashboard-reward-card.js
> fix missing copy value

- src/c/dashboard-reward-card.js
- src/root/project-edit-reward.js
Add limit reward checkbox to dashboard reward box. Project owners can now update limit count even when the reward is not updatable anymore.
> Limit reward

- src/vms/payment-vm.js
New users do not have an address yet.
> fix 'Cannot read property "city" of null'

- src/c/address-form.js
- src/root/surveys-show.js
Implement new address form component that will be used across the site.
> new address form

- src/c/dashboard-open-question.js
- src/root/surveys-show.js
> fixes empty field after edit

- src/c/project-contribution-report-header.js
- src/root/projects-contribution-report.js
- src/vms/projects-contribution-report-vm.js
Adds delivery status filter to contributions report
> Add delivery status to contribution report

- src/root/projects-contribution-report.js
- src/vms/projects-contribution-report-vm.js
> Adds missing survey filter

- src/c/admin-project-details-card.js
- src/c/cancel-project-modal-content.js
- src/c/project-data-stats.js
- src/c/project-share-box.js
- src/c/user-balance-request-modal-content.js
- src/c/user-balance-transaction-row.js
- src/c/user-balance.js
- src/h.js
- src/root/insights.js
- Added rejected projects on failed projects contributions
- User can cancel the project any time whe not (rejected, draft)
- Support to handle with has_cancelation_request
> User balance part2

- src/c/survey-preview.js
- src/root/surveys-show.js
@devton this requires user address refactor to work
> allow empty answers and fill with user address by default [#148746291]

- src/c/dashboard-multiple-choice-question.js
- src/c/dashboard-open-question.js
- src/c/survey-create-preview.js
- src/root/survey-create.js
- src/vms/survey-vm.js
Add inline error to survey questions
> add inline error to survey questions

- package-lock.json
- package.json
Commit npm lock file to normalize dependencies across different environments.
> add missing dependency, commit npm lock file

- src/c/project-user-card.js
- src/root/insights.js
- use can_cancel to show btn
- hide and unlink user when deactivated
> use can cancel to show btn

- gulpfile.js
- package-lock.json
- package.json
- rollup.config.js
- src/c/copy-text-input.js
This fixes the copy input component.
> Fix copy input

- src/c/address-form.js
- src/c/edit-reward-card.js
- src/c/payment-credit-card.js
- src/c/project-reward-card.js
- src/c/reward-select-card.js
- src/c/shipping-fee-input.js
- src/root/projects-explore.js
- src/root/start.js
Always pass value in hash to avoid weird mithril behaviour.
> fix options value

- src/c.js
- src/h.js
- src/root/footer.js
- src/root/press.js
Creates the press page in mithril
> Create press page

- src/c/user-notifications.js
Implements newsletter cards on user dashboard
> implement newsletter cards

- src/c/user-notifications.js
> fixes newsletter signup

- src/c/edit-reward-card.js
- src/root/projects-payment.js
- src/vms/reward-vm.js
this was being called by selectFee which requires a reward object
> fix getFees

- src/c/edit-reward-card.js
- src/root/project-edit-reward.js
Adds rules to display rewards dashboard when subscription project
> New subscription reward dash

- src/c/project-description-video-edit.js
- src/root/project-edit-description.js
- src/root/project-edit.js
- src/vms/project-description-video-vm.js
- src/vms/project-vm.js
Adds a new description dashboard that for now will be used for the new subscription projects.
> adds description dashboard for sub projects

- src/c/project-dashboard-menu.js
- src/root/project-edit-start.js
- src/root/project-edit.js
- src/vms/project-vm.js
implements a new dashboard tab for subscription projects.
> implements new start tab for sub projects in draft

- src/c/project-card.js
> Add project card subscriptions mode

- src/c/project-card-edit.js
- src/c/project-goal-edit-card.js
- src/c/project-header.js
- src/vms/project-card-vm.js
add cover image upload and goal validations
> cover image

- spec/components/project-about.spec.js
- spec/components/project-header.spec.js
- spec/components/project-sidebar.spec.js
- spec/lib/mocks/goals.mock.js
- src/c/address-tag.js
- src/c/category-tag.js
- src/c/facebook-button.js
- src/c/project-about.js
- src/c/project-goals-box.js
- src/c/project-goals-edit.js
- src/c/project-header-title.js
- src/c/project-header.js
- src/c/project-highlight.js
- src/c/project-main.js
- src/c/project-mode.js
- src/c/project-reward-card.js
- src/c/project-sidebar.js
- src/c/project-tabs.js
- src/c/project-user-card.js
- src/root/project-edit-reward.js
- src/root/projects-show.js
- src/vms/project-goals-vm.js
- src/vms/project-vm.js
Adds new state to project details components
> add new subscription project details page

- src/c/project-header-title.js
- src/c/project-header.js
- src/c/project-sidebar.js
- src/c/project-user-card.js
Fixes some layout bugs on the new projet details page
> New project details fixes

- src/c.js
- src/c/faq-box.js
- src/c/project-reward-card.js
- src/c/project-sidebar.js
- src/root/projects-subscription-checkout.js
- src/root/projects-subscription-contribution.js
Add first new page on the new subscription flow
> add subscription/start page

- src/root/surveys-show.js
https://sentry-service.catarse.me/sentry/catarse-rails/issues/2501/
> make sure user info is loaded

- src/c/reward-select-card.js
- src/root/projects-subscription-contribution.js
> fixes copy issues

- src/c/project-reward-card.js
- src/root/projects-subscription-checkout.js
First changes to subscription checkout
> implement checkout changes for subscriptions

- src/c.js
- src/c/project-dashboard-menu.js
- src/root/projects-subscription-report.js
> add sub report page[#151370722]

- src/c/project-goals-box-dashboard.js
- src/c/project-goals-box.js
- src/c/project-insights-sub.js
- src/c/project-insights.js
- src/root/insights.js
Mostly static content for now. Need to update when we have the API working.
> Sub insights

- src/c/project-dashboard-menu.js
- src/c/project-goals-box-dashboard.js
- src/c/project-insights-sub.js
- src/root/surveys.js
- remove survey tab from sub projects
- fix goal card layout
- fix share card layout
> sub dashboard fixes

- src/c/project-about.js
- src/c/project-goals-box.js
- src/c/project-header.js
- src/c/project-main.js
- src/c/project-sidebar.js
- src/root/projects-show.js
- src/vms/project-vm.js
Add dynamic info to project page.
> add sub details to project page

- src/c/project-goals-box.js
- src/c/project-sidebar.js
Should show current goal on project page.
> fix initial goal [#152894684]

- src/api.js
> Fix auth url

- src/c/project-header.js
Make the background image layer a bit lighter
> Updating background image class

- src/c/dashboard-subscription-card.js
- src/root/projects-subscription-report.js
Adjusting the table in subscription reports. There was not enough space to show all the information.
> Report sub fixes

- src/c/project-header.js
Depends on this PR: https://github.com/catarse/catarse/pull/2863
> Fix user subscriptiosn on project page

- src/root/projects-subscription-report.js
Just adjusting the styles in Sub Reports Page's filters, so it looks better.
> adjusting filters style in sub project

- src/c/payment-credit-card.js
- src/c/payment-form.js
- src/c/payment-slip.js
- src/c/project-goals-box.js
- src/c/project-sidebar.js
- src/modules.js
- src/root/projects-show.js
- src/root/projects-subscription-checkout.js
- src/root/projects-subscription-thank-you.js
- src/vms/common-payment-vm.js
- src/vms/project-vm.js
> Finish payment process

- src/c/project-about.js
- src/c/project-goals-box.js
- src/c/project-main.js
- src/c/project-rewards.js
> fix goals box load

- src/vms/common-payment-vm.js
Updates the user when sending subscription payment.
> update user when processing subscription payment

- src/c/project-reward-card.js
- src/c/reward-select-card.js
- src/h.js
- src/root/projects-subscription-checkout.js
- src/vms/project-vm.js
fixes subscription/checkout routing
> fixes subscription/checkout routing

- src/root/projects-subscription-checkout.js
> fixes next billing date

- src/c/project-main.js
- src/h.js
- src/root/projects-subscription-checkout.js
- src/vms/project-vm.js
fixes subscription auth re route
> fixes subscription auth re route

- package-lock.json
- package.json
- src/api.js
- updates mithril-postgrest version
- wraps common requests, add platform-code header
> add global header to common requests

- src/root/projects-subscription-thank-you.js
- src/vms/common-payment-vm.js
- Fixes user thumb
- Fixes slip copy
> fixes some issues with subscription thank you page

- src/root/projects-subscription-thank-you.js
> fixes thank you page

- src/root/projects-subscription-report.js
- src/vms/common-payment-vm.js
Fixes user payment update payload.
> fixes user payment update payload

- src/root/projects-subscription-thank-you.js
- src/vms/common-payment-vm.js
Refactor payment processing, fixes thank you.
> Fixes subscription checkout

- src/c/project-share-box.js
- src/c/project-tabs.js
- src/h.js
Temporarily remove embed on subscription projects.
Adds subscription top bar CTA
> New fixes for subscriptions

- src/c/project-tabs.js
> Fixes button copy

- src/c/project-header.js
Fixes bug with subscription contribubtion when coming from mithril routes.
> Add check to see if subscription belongs to header

- gulpfile.js
- karma.conf.js
- package-lock.json
- package.json
- rollup.config.js
- rollup.config.spec.js
- spec/lib/mocks/postgrest-requests.mock.js
- src/api.js
- src/c/project-edit-save-btn.js
- src/h.js
- src/models.js
- src/root/admin-notifications.js
> Feature notification admin

- src/root/projects-subscription-checkout.js
we don't have a default selected reward anymore
> fix selected reward

- src/root/footer.js
Includes a link to the about us page (https://crowdfunding.catarse.me/quem-somos) in our footer. I also removed some 'NOVIDADE' badges.
> Including About us in footer

- src/root/start.js
Includes a link to Assinaturas Landing Page in our 'Start your project' page
> Include a card linking to Assinaturas Landing Page in start

- src/root/projects-show.js
Move post details page to mithril routing
> Fixes posts page routes

- src/c/project-tabs.js
Fixes issue with iframe redrawing that was breaking projects/show youtube videos on scroll.
> Fixes iframe redraw issue

- src/c/payment-slip.js
- src/h.js
- src/root/projects-subscription-thank-you.js
- src/vms/common-payment-vm.js
Wait for payment information after sending payment. Display more accurate info on the subscription thank you page.
> Feature wait payment response

- src/c/user-subscription-box.js
Shows the next slip payment expiration date and provides a link
> Adds next boleto link with expiration date info

- src/vms/common-payment-vm.js
Fixes some issues with subscription payment
> Fixes some issues with subscription payment

- spec/components/cancel-project-modal-content.spec.js
- spec/components/project-cancel-button.spec.js
- src/c/cancel-project-modal-content.js
- src/c/project-cancel-button.js
Load redactor with mithril, this is necessary so redactor will get loaded when going through mithril routes.
> fix project cancel button

- src/c/insights-info-box.js
- src/c/project-insights-sub.js
- src/models.js
- src/root/insights.js
- src/vms/subscription-vm.js
Add new subscribers and canceled subscribers info boxes.
> add some sub info box to insights page

- src/c/project-user-card.js
project_id wasn't being passed when loading project page via mithril route
> fix project owner direct message

- src/vms/common-payment-vm.js
Add new field to common payment request
> Add credit card owner document to common credit card payment

- src/vms/common-payment-vm.js
Avoid creating new subscription when payment attempt fails.
> Send payment_id when trying to re-pay failed payment attempt

- src/c/faq-box.js
- src/root/projects-subscription-contribution.js
Creates subscription edit state.
> Creates subscription start new edit state

- src/c/download-reports.js
- src/root/projects-subscription-report-download.js
We need to inform the users that the data being download is a sensible data.
> Warning on report download about sensible data

- spec/components/payment-credit-card.spec.js
- src/c/payment-credit-card.js
- src/c/payment-slip.js
- src/c/subscription-edit-modal.js
- src/c/user-subscription-box.js
- src/models.js
- src/root/projects-subscription-checkout.js
- src/vms/common-payment-vm.js
- src/vms/subscription-vm.js
Allow subscription users to edit their currently active subscription.
> Subscription edit/upgrade

- src/c/payment-credit-card.js
- src/c/payment-slip.js
- src/c/reward-select-card.js
- src/c/user-subscription-box.js
- src/root/projects-subscription-contribution.js
- src/vms/common-payment-vm.js
> Fix subscription edit flow

- src/vms/common-payment-vm.js
> Send credit card id when common payment

- src/c/payment-credit-card.js
- src/c/payment-slip.js
- src/c/subscription-edit-modal.js
- src/h.js
- src/root/projects-subscription-checkout.js
- src/vms/subscription-vm.js
> fixes some parameters and copies

- src/root/publish.js
Only current term should be allowed to be accepted.
> fix publish logic

- src/vms/common-payment-vm.js
> Only add payment_id to subscription thank you if it exists

- src/root/project-edit-start.js
Swapping the Welcome youtube video in Assinaturas Start page (dashboard) for a Ebook.
> Include Assinaturas ebook in Edit Start Page

- src/c/project-data-chart.js
- src/c/project-insights.js
> Limit entries for visitors insihgt chart

- src/c/user-subscription-box.js
On feature #155246263 was not showing the right reward, next payment and next payment method
> Show edited subscription details

- src/c/project-insights-sub.js
- src/c/project-insights.js
> data chart title copy fix

- src/c/user-subscription-box.js
Fixed bug for error showing the reward change when it had no edition (#157426205)
Don't show subscriptions edition when subscription is inactive (#157426425).
> Fix reward change

- src/c/admin-list.js
- src/root/admin-balance-tranfers.js
- src/vms/balance-transfer-filter-vm.js
Add action to admin process transfers via admin
> Feature admin process transfers

- src/root/admin-contributions.js
add action to admin chargeback a batch of gateway_ids that are paid
> add component to chargeback a batch of ds of gateway_ids

- src/c/user-balance-transaction-row.js
mapping new fields to balance transactions copy
> add from_user_name and to_user_name to balance_transactions copy

- src/c/project-report-disrespect-rules.js
> fix typo #157690984

- src/c/user-subscription-box.js
re-subscribe button was not appearing #157199662
> Show subscribe again button

- spec/components/project-report.spec.js
- src/c/project-report.js
Just a minor adjustment on the style of the report button on the project page. It is too big, so we are making it a bit smaller. @adrianob @vicnicius @devton @grpse I never know what to check on the checklist above 😄 What should I check in this case?
> Making the report button a bit smaller

- package-lock.json
- src/c/project-insights-sub.js
- src/c/project-insights.js
Implements 30 days rule in the right project mode insight
> Fix visitors per day insight

- spec/components/dashboard-subscription-card-detail.spec.js
- spec/lib/mocks/user-details.mock.js
- src/c/dashboard-subscription-card-detail.js
On loading country by it's id, the component was not checking if the user address in null or not
> fix subscribers details #157921787

- src/root/project-edit-welcome.js
Some minor styles fixes
It makes the 'Email content' form field a bit smaller and also adjust the 'Reward' select to make it better.
> Fix welcome reward message form styles

- src/c/user-contributed-box.js
'Pagamento recusado' to 'Pagamento não realizado' on locales
> change copy of refused to boleto #158031883

- src/c/payment-credit-card.js
With new installment options the user should see the total amount the him will pay for with taxes.
> show total amount of installments #158173919

- src/c/payment-credit-card.js
transform save card in a clicable card
> Save card card

- src/c/project-about.js
- src/c/project-reward-card.js
- src/c/project-reward-list.js
- src/root/projects-contribution.js
- src/root/projects-reward.js
added installments indication on top of selection of possible rewards and contributions
> Show 6x installment on contribution selected

- src/root/project-edit-reward.js
It moves the ebook link on the Rewards page in Project Dashboard to the side column.
> Moving ebook link to the side of the page

- src/root/projects-subscription-thank-you.js
- src/root/thank-you.js
When subscription is created it should generate an event on moments database.
> moments event when subscription or contribution are created #157967203

- spec/lib/mocks/subscription-version.mock.js
- src/c/user-subscription-box.js
> add warning when subscription is started and last payment is refused

- src/root/projects-subscription-checkout.js
Fix error when fetching rewards on subscription checkout page
> Fix subscription checkout

- package-lock.json
- package.json
- webpack.config.js
> Improves webpack configuration, re-enable babel env preset

- package-lock.json
- package.json
- src/c/menu-search.js
- src/c/project-contribution-report-content-card.js
- src/c/project-user-card.js
- src/h.js
- webpack.config.js
Enabling `webpack-dev-server` for faster development workflow.
> Enable webpack dev server

- README.md
> Update readme, add webpack-dev-server instructions

- spec/components/admin-notification-details.spec.js
- spec/lib/mocks/admin-notification-details.mock.js
- src/c/admin-subscription-detail.js
Show subscription notifications in order and a button to load older ones
> Order subscriptions notification

- src/c/project-insights-sub.js
- src/root/insights.js
- src/root/posts.js
- src/root/project-edit-welcome.js
- src/root/projects-fiscal.js
- src/root/projects-subscription-report.js
Added catarse loader to loading parts of subscription dashboard
> Add loaders to subs menu and growth table

- legacy/spec/components/dashboard-subscription-card-detail-payment-entry.spec.js
- legacy/spec/components/dashboard-subscription-card-detail.spec.js
- legacy/spec/lib/mocks/payments.mock.js
- legacy/src/c/dashboard-subscription-card-detail-payment-history-entry.js
- legacy/src/c/dashboard-subscription-card-detail-payment-history.js
- legacy/src/c/dashboard-subscription-card-detail-subscription-details.js
- legacy/src/c/dashboard-subscription-card-detail-user-address.js
- legacy/src/c/dashboard-subscription-card-detail-user-profile.js
- legacy/src/c/dashboard-subscription-card-detail.js
- legacy/src/root/projects-subscription-report.js
Show payment history for each subscription
> subscription payment history entries #158551037

- legacy/spec/components/user-settings-address.spec.js
- legacy/spec/components/user-settings-help.spec.js
- legacy/spec/components/user-settings-responsible.spec.js
- legacy/spec/components/user-settings-saved-credit-cards.spec.js
- legacy/src/c/user-settings-address.js
- legacy/src/c/user-settings-help.js
- legacy/src/c/user-settings-responsible.js
- legacy/src/c/user-settings-saved-credit-cards.js
- legacy/src/c/user-settings.js
- legacy/src/root/project-edit-user-settings.js
Spliting user settings into different components to add help for project edit user settings.
> split user settings forms #158139162

- legacy/src/c/user-settings-help.js
- legacy/src/c/user-settings-responsible.js
> Removing period from help component

- legacy/src/c/address-form.js
> limit address max chars

- legacy/src/c/filter-dropdown-number-range.js
- legacy/src/c/filter-text.js
- legacy/src/root/projects-subscription-report.js
- legacy/src/vms/projects-subscription-report-vm.js
Add two more filters to subscriptions search
> total paid and paid count filters added #158587322 #158551900

- legacy/src/c/filter-dropdown-number-range.js
- legacy/src/root/projects-subscription-report.js
adding min value to input fields
> add min value 0 to input number fields #158587322 #158551900

- legacy/src/c/filter-dropdown-number-range.js
- legacy/src/root/projects-subscription-report.js
On number input replace anything that is not a number and use math.abs to ensure that the number is positive.
> using abs value from number input #158587322 #158551900

- legacy/src/c/filter-dropdown-number-range.js
- legacy/src/c/filter-text.js
- legacy/src/root/projects-subscription-report.js
Signed-off-by: Gilberto Ribeiro <gilbertoribeiropazdarosa@gmail.com>
Fixes on filters styles and behavior
> adding fixes to filters for subscriptions report page #159679966

- .babelrc
- legacy/src/c.js
- package-lock.json
- package.json
> Add polyfill for older browser versions

- legacy/src/c/user-balance-request-modal-content.js
Fix account type name translation
> fixing translation for confirmation modal of withdraw request #159591681
